import { IconArrowRight, IconSparkles } from "@tabler/icons-react"

import { Avatar, AvatarFallback } from "@/components/ui/avatar"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"

export type Reviewer = { id: string; name: string; emoji: string; synthetic: boolean; priorities: string[]; commentCount: number }
export type HallEntry = { ghostId: string; ghostName: string; emoji: string; resurrections: number; findings: number; bugsPredicted: number; accuracy: number }

export function DataTable({ reviewers, entries, onOpenSeance }: { reviewers: Reviewer[]; entries: HallEntry[]; onOpenSeance: () => void }) {
  return <Tabs defaultValue="reviewers" className="w-full flex-col justify-start gap-6"><div className="flex items-center justify-between px-4 lg:px-6"><TabsList className="h-9"><TabsTrigger value="reviewers">Reviewers</TabsTrigger><TabsTrigger value="history">Hall of fame</TabsTrigger></TabsList><Button size="sm" onClick={onOpenSeance}><IconSparkles />Ask a ghost</Button></div><TabsContent value="reviewers" className="m-0 px-4 lg:px-6"><Card><CardHeader><CardTitle>Ghost roster</CardTitle><CardDescription>Reviewers reconstructed from the repository’s own history.</CardDescription></CardHeader><CardContent><Table><TableHeader><TableRow><TableHead>Reviewer</TableHead><TableHead className="hidden md:table-cell">Focus</TableHead><TableHead className="text-right">Historic comments</TableHead></TableRow></TableHeader><TableBody>{reviewers.map((reviewer) => <TableRow key={reviewer.id}><TableCell><div className="flex items-center gap-3"><Avatar className="size-8 rounded-lg"><AvatarFallback className="rounded-lg bg-primary/10">{reviewer.emoji}</AvatarFallback></Avatar><div><p className="font-medium">{reviewer.name}</p><p className="text-xs text-muted-foreground">{reviewer.synthetic ? "Future perspective" : "Remembered reviewer"}</p></div></div></TableCell><TableCell className="hidden max-w-64 truncate text-muted-foreground md:table-cell">{reviewer.priorities[0] ?? "General review"}</TableCell><TableCell className="text-right tabular-nums">{reviewer.commentCount}</TableCell></TableRow>)}</TableBody></Table>{!reviewers.length && <p className="py-10 text-center text-sm text-muted-foreground">The archive has no ghosts yet.</p>}</CardContent></Card></TabsContent><TabsContent value="history" className="m-0 px-4 lg:px-6"><Card><CardHeader><CardTitle>Repository hall of fame</CardTitle><CardDescription>Accuracy improves as the council records more verdicts.</CardDescription></CardHeader><CardContent><Table><TableHeader><TableRow><TableHead>Ghost</TableHead><TableHead className="text-right">Summoned</TableHead><TableHead className="text-right">Findings</TableHead><TableHead className="text-right">Accuracy</TableHead></TableRow></TableHeader><TableBody>{entries.map((entry) => <TableRow key={entry.ghostId}><TableCell className="font-medium">{entry.emoji} {entry.ghostName}</TableCell><TableCell className="text-right tabular-nums">{entry.resurrections}</TableCell><TableCell className="text-right tabular-nums">{entry.findings}</TableCell><TableCell className="text-right"><Badge variant="outline">{Math.round(entry.accuracy * 100)}%</Badge></TableCell></TableRow>)}</TableBody></Table>{!entries.length && <div className="py-10 text-center"><p className="text-sm text-muted-foreground">Run a council review to build the record.</p><Button variant="link" onClick={onOpenSeance}>Explore a ghost first <IconArrowRight /></Button></div>}</CardContent></Card></TabsContent></Tabs>
}
